# Generated by Django 5.2.1 on 2026-09-27 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0030_annulation_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], max_length=10)),
                ('minutes_retard', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minutes de retard')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages_seance', to='dashboard.inscription')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage de séance',
                'verbose_name_plural': 'Pointages de séance',
                'ordering': ['inscription__etudiant__nom', 'inscription__etudiant__prenom'],
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif communiqué')),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=12)),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire_decision', models.TextField(blank=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_decidees', to=settings.AUTH_USER_MODEL)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_soumises', to=settings.AUTH_USER_MODEL)),
                ('pointage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='justification', to='vie_scolaire.pointage')),
            ],
            options={
                'verbose_name': 'Justification de présence',
                'verbose_name_plural': 'Justifications de présence',
                'ordering': ['-soumis_le'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du cours')),
                ('heure_debut', models.TimeField(verbose_name='Début')),
                ('heure_fin', models.TimeField(verbose_name='Fin')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='dashboard.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='dashboard.ecolesettings')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='dashboard.enseignant')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='dashboard.programmematiere')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-date', 'heure_debut', 'classe__nom_classe'],
            },
        ),
        migrations.AddField(
            model_name='pointage',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='vie_scolaire.seance'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['ecole', 'date', 'classe'], name='seance_ecole_date_classe_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['ecole', 'date', 'enseignant'], name='seance_ecole_date_prof_idx'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.CheckConstraint(condition=models.Q(('heure_debut__lt', models.F('heure_fin'))), name='seance_heures_croissantes'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('classe', 'date', 'heure_debut'), name='uniq_seance_classe_debut'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('enseignant', 'date', 'heure_debut'), name='uniq_seance_prof_debut'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('seance', 'inscription'), name='uniq_pointage_seance_inscription'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minutes_retard__gt', 0), ('statut', 'retard')), models.Q(('minutes_retard__isnull', True), ('statut__in', ['present', 'absent'])), _connector='OR'), name='pointage_retard_minutes_coherentes'),
        ),
    ]
