# Generated by Django 5.2.1 on 2026-09-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_creancescolaire_date_echeance_and_more'),
        ('vie_scolaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='dashboard.salle', verbose_name='Salle'),
        ),
    ]
