# Generated by Django 5.2.1 on 2026-09-27 01:29

import logging

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def reprendre_affectations_courantes(apps, schema_editor):
    """Reprendre uniquement le pointeur actuel, sans inventer les transferts passés."""
    Inscription = apps.get_model('dashboard', 'Inscription')
    AffectationClasse = apps.get_model('parcours_scolaire', 'AffectationClasse')
    lot = []
    alias = schema_editor.connection.alias
    date_reprise = timezone.localdate()
    ignores_incoherents = 0
    ignores_hors_annee = 0
    inscriptions = Inscription.objects.using(alias).filter(
        statut='active', classe__isnull=False,
    ).select_related('classe', 'annee_scolaire', 'etudiant')
    for inscription in inscriptions.iterator(chunk_size=500):
        classe = inscription.classe
        annee = inscription.annee_scolaire
        if (classe.ecole_id != inscription.ecole_id or
                classe.annee_scolaire_id != inscription.annee_scolaire_id or
                inscription.etudiant.ecole_id != inscription.ecole_id):
            ignores_incoherents += 1
            continue
        # Seule la classe connue au jour de la reprise est attestée.
        debut = max(inscription.date_inscription, annee.date_debut, date_reprise)
        if debut > annee.date_fin:
            ignores_hors_annee += 1
            continue
        lot.append(AffectationClasse(
            inscription_id=inscription.pk, classe_id=classe.pk,
            date_debut=debut, origine='reprise',
        ))
        if len(lot) == 500:
            AffectationClasse.objects.using(alias).bulk_create(lot, batch_size=500)
            lot.clear()
    if lot:
        AffectationClasse.objects.using(alias).bulk_create(lot, batch_size=500)
    if ignores_incoherents or ignores_hors_annee:
        logging.getLogger(__name__).warning(
            'Reprise des affectations : %s pointeur(s) incohérent(s) et %s inscription(s) hors année ignorée(s). '
            'Exécutez auditer_affectations après la migration.',
            ignores_incoherents, ignores_hors_annee,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0031_regle_bulletin_annuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début inclus')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin exclue')),
                ('origine', models.CharField(choices=[('saisie', 'Saisie datée'), ('reprise', 'Reprise des données existantes')], default='saisie', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_eleves', to='dashboard.classe')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_classe', to='dashboard.inscription')),
            ],
            options={
                'verbose_name': 'Affectation de classe',
                'verbose_name_plural': 'Affectations de classe',
                'ordering': ['inscription', 'date_debut'],
                'indexes': [models.Index(fields=['inscription', 'date_debut'], name='affect_insc_debut_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='affectation_intervalle_positif'), models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('inscription',), name='uniq_affectation_ouverte_insc')],
            },
        ),
        migrations.RunPython(reprendre_affectations_courantes, migrations.RunPython.noop),
    ]
