# Generated by Django 5.2.1 on 2026-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_reconcilier_ecoles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('unassigned', 'À définir'), ('school_admin', 'Administrateur'), ('director', 'Direction'), ('secretary', 'Secrétariat'), ('accountant', 'Comptabilité'), ('teacher', 'Enseignant')], default='unassigned', max_length=20),
        ),
    ]
