# Generated by Django 5.2.1 on 2026-09-26 23:23

import dashboard.private_media
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_profile_role_unassigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bulletin', 'Bulletin de notes'), ('frequentation', 'Certificat de fréquentation'), ('attestation_scolarite', 'Attestation de scolarité'), ('certificat_inscription', 'Certificat d’inscription'), ('autre', 'Autre document administratif')], max_length=30, verbose_name='Type de document')),
                ('code', models.SlugField(blank=True, default='', help_text='Obligatoire pour un document libre ; vide pour les documents standard.', max_length=80, verbose_name='Code du modèle personnalisé')),
                ('titre', models.CharField(max_length=180, verbose_name='Titre du document')),
                ('entete', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1200)], verbose_name='En-tête')),
                ('corps', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Texte principal')),
                ('mention', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mention')),
                ('pied_de_page', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1200)], verbose_name='Pied de page')),
                ('titre_signataire', models.CharField(blank=True, max_length=100, verbose_name='Titre du signataire')),
                ('afficher_logo', models.BooleanField(default=True, verbose_name='Afficher le logo')),
                ('afficher_cachet', models.BooleanField(default=True, verbose_name='Afficher le cachet')),
                ('afficher_signature', models.BooleanField(default=True, verbose_name='Afficher la signature')),
                ('actif', models.BooleanField(default=True, verbose_name='Modèle actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_documents', to='dashboard.ecolesettings', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['type_document', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bulletin', 'Bulletin de notes'), ('frequentation', 'Certificat de fréquentation'), ('attestation_scolarite', 'Attestation de scolarité'), ('certificat_inscription', 'Certificat d’inscription'), ('autre', 'Autre document administratif')], max_length=30)),
                ('numero_document', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Numéro du document')),
                ('code_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, storage=dashboard.private_media.PrivateMediaStorage(), upload_to='documents_emis/', verbose_name='Fichier PDF privé')),
                ('modele_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Plan lors de l’émission')),
                ('donnees_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données lors de l’émission')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annulé')], default='valide', max_length=10)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_emis', to='dashboard.anneescolaire', verbose_name='Année scolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_emis', to='dashboard.ecolesettings', verbose_name='École')),
                ('emis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_emis', to='dashboard.etudiant', verbose_name='Élève')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_emis', to='dashboard.inscription', verbose_name='Inscription annuelle')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_emis', to='dashboard.modeledocument', verbose_name='Modèle de document')),
            ],
            options={
                'verbose_name': 'Document émis',
                'verbose_name_plural': 'Documents émis',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddConstraint(
            model_name='modeledocument',
            constraint=models.UniqueConstraint(fields=('ecole', 'type_document', 'code'), name='uniq_modele_document_ecole_type_code'),
        ),
        migrations.AddIndex(
            model_name='documentemis',
            index=models.Index(fields=['ecole', 'etudiant', 'date_emission'], name='document_ecole_eleve_date_idx'),
        ),
    ]
