# Generated by Django 5.2.1 on 2026-09-27 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_modeles_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('1AP', '1ère année fondamentale'), ('2AP', '2e année fondamentale'), ('3AP', '3e année fondamentale'), ('4AP', '4e année fondamentale'), ('5AP', '5e année fondamentale'), ('6AP', '6e année fondamentale'), ('7AP', '7e année fondamentale'), ('8AP', '8e année fondamentale'), ('9AP', '9e année fondamentale (DEF)'), ('1AS', '10e année commune'), ('2AS', '11e année'), ('TLE', '12e année / Terminale'), ('TL', 'Terminale L (ancien code)'), ('TS', 'Terminale S (ancien code)'), ('TC', 'Terminale C (ancien code)')], max_length=50, verbose_name='Niveau Scolaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='serie',
            field=models.CharField(blank=True, help_text='Par exemple : Lettres, Sciences, SES, TLL, TAL, TSS, TSEco, TSExp ou TSE.', max_length=50, null=True, verbose_name='Série (pour le lycée)'),
        ),
        migrations.AlterField(
            model_name='programmematiere',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Coefficient'),
        ),
        migrations.AddConstraint(
            model_name='programmematiere',
            constraint=models.CheckConstraint(condition=models.Q(('coefficient__gte', 1)), name='coeff_programme_positif'),
        ),
    ]
