# Generated by Django 5.2.1 on 2026-09-27 01:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_niveaux_mali_coefficients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_evaluation', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=20)),
                ('titre', models.CharField(max_length=180, verbose_name="Titre de l'évaluation")),
                ('type_evaluation', models.CharField(blank=True, max_length=50, verbose_name="Type d'évaluation")),
                ('date_evaluation', models.DateField(verbose_name="Date de l'évaluation")),
                ('bareme', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Barème')),
                ('poids', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids dans la matière')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='dashboard.ecolesettings')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='dashboard.programmematiere')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['periode_evaluation', 'date_evaluation', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResultatEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Note obtenue')),
                ('annule', models.BooleanField(default=False, verbose_name='Résultat annulé')),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_evaluation_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='dashboard.evaluation')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_evaluation', to='dashboard.inscription')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_evaluation_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_evaluation_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': "Résultat d'évaluation",
                'verbose_name_plural': "Résultats d'évaluation",
                'ordering': ['evaluation', 'inscription__etudiant__nom', 'inscription__etudiant__prenom'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['ecole', 'programme', 'periode_evaluation'], name='eval_ecole_programme_per_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('bareme__gt', 0)), name='eval_bareme_positif'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('poids__gt', 0)), name='eval_poids_positif'),
        ),
        migrations.AddConstraint(
            model_name='resultatevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation', 'inscription'), name='uniq_resultat_eval_inscription'),
        ),
        migrations.AddConstraint(
            model_name='resultatevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('valeur__gte', 0)), name='resultat_valeur_non_negative'),
        ),
    ]
