# Generated by Django 5.2.1 on 2026-09-27 01:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_annulation_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleBulletinAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('fondamental_1', 'Fondamental 1er cycle'), ('fondamental_2', 'Fondamental 2e cycle'), ('lycee', 'Lycée')], max_length=20, verbose_name='Cycle')),
                ('poids_trimestre_1', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids du 1er trimestre')),
                ('poids_trimestre_2', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids du 2e trimestre')),
                ('poids_trimestre_3', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids du 3e trimestre')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_bulletin_annuel', to='dashboard.anneescolaire', verbose_name='Année scolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_bulletin_annuel', to='dashboard.ecolesettings', verbose_name='École')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regles_bulletin_annuel_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Règle de bulletin annuel',
                'verbose_name_plural': 'Règles de bulletin annuel',
                'ordering': ['-annee_scolaire__annee', 'cycle'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'cycle'), name='uniq_regle_bulletin_ecole_annee_cycle'), models.CheckConstraint(condition=models.Q(('poids_trimestre_1__gte', 0), ('poids_trimestre_2__gte', 0), ('poids_trimestre_3__gte', 0)), name='regle_bulletin_poids_non_negatifs'), models.CheckConstraint(condition=models.Q(('poids_trimestre_1__gt', 0), ('poids_trimestre_2__gt', 0), ('poids_trimestre_3__gt', 0), _connector='OR'), name='regle_bulletin_somme_positive'), models.CheckConstraint(condition=models.Q(models.Q(('valide_le__isnull', True), ('valide_par__isnull', True)), models.Q(('valide_le__isnull', False), ('valide_par__isnull', False)), _connector='OR'), name='regle_bulletin_validation_complete')],
            },
        ),
    ]
