# Generated by Django 5.2.1 on 2026-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_regle_bulletin_annuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='academie',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Académie / CAP'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='adresse_etablissement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse complète de l’établissement'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='etablissement_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de l’établissement complet'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='ministere',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ministère de tutelle'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='lieu_delivrance',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Lieu de délivrance'),
        ),
    ]
