# Generated by Django 5.2.1 on 2026-09-27 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_certificat_identite_ecole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creancescolaire',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date limite d'exigibilité"),
        ),
        migrations.AddField(
            model_name='creancescolaire',
            name='remise_montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de remise (FCFA)'),
        ),
        migrations.AddField(
            model_name='creancescolaire',
            name='remise_type',
            field=models.CharField(choices=[('aucune', 'Aucune'), ('fratrie', 'Remise fratrie'), ('bourse', 'Bourse d’étude / Cas social'), ('personnel', 'Enfant du personnel'), ('autre', 'Autre remise exceptionnelle')], default='aucune', max_length=30, verbose_name='Type de remise'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recu_code_securise',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Code sécurisé de vérification'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. Transaction / Chèque'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='telephone_payeur',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° Tél. Payeur (Mobile Money)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Orange Money', 'Orange Money Mali'), ('Wave', 'Wave Mali'), ('Moov Money', 'Moov Africa Malitel'), ('Sama Money', 'Sama Money'), ('Chèque', 'Chèque'), ('Virement Bancaire', 'Virement Bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de Paiement'),
        ),
        migrations.CreateModel(
            name='PlanEcheancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tranche', models.CharField(max_length=100, verbose_name='Intitulé de la tranche')),
                ('motif', models.CharField(choices=[('Frais de Scolarité', 'Frais de Scolarité'), ("Frais d'Inscription", "Frais d'Inscription"), ('Cotisation APEM', 'Cotisation APEM'), ('Tenue Scolaire', 'Tenue Scolaire'), ('Repas Scolaire', 'Repas Scolaire'), ('Autres', 'Autres')], default='Frais de Scolarité', max_length=100, verbose_name='Motif')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant exigible (FCFA)')),
                ('date_echeance', models.DateField(verbose_name="Date limite d'exigibilité")),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'échéance")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_echeancier', to='dashboard.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_echeancier', to='dashboard.classe', verbose_name="Classe ciblée (vide = tout l'établissement)")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_echeancier', to='dashboard.ecolesettings', verbose_name='École')),
            ],
            options={
                'verbose_name': "Plan d'échéancier scolaire",
                'verbose_name_plural': "Plans d'échéanciers scolaires",
                'ordering': ['ordre', 'date_echeance', 'nom_tranche'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=50, verbose_name='Nom de la salle')),
                ('code_salle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code de la salle')),
                ('capacite', models.PositiveSmallIntegerField(default=50, verbose_name='Capacité')),
                ('type_salle', models.CharField(choices=[('standard', 'Salle de cours standard'), ('informatique', 'Salle informatique'), ('laboratoire', 'Laboratoire de sciences'), ('polyvalente', 'Salle polyvalente / Réunion')], default='standard', max_length=30, verbose_name='Type de salle')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='dashboard.ecolesettings', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
                'ordering': ['nom_salle'],
            },
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='dashboard.salle', verbose_name='Salle de cours'),
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('telephone_principal', models.CharField(max_length=30, verbose_name='Téléphone principal')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('quartier', models.CharField(blank=True, default='Bamako', max_length=100, verbose_name='Quartier / Commune')),
                ('canal_prefere', models.CharField(choices=[('sms', 'SMS Mobile'), ('whatsapp', 'WhatsApp'), ('appel', 'Appel téléphonique'), ('email', 'Email')], default='sms', max_length=20, verbose_name='Canal de communication favori')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='dashboard.ecolesettings', verbose_name='École')),
            ],
            options={
                'verbose_name': "Tuteur / Parent d'élève",
                'verbose_name_plural': "Tuteurs / Parents d'élèves",
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='NotificationParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('absence', 'Avis d’absence'), ('retard', 'Notification de retard'), ('rappel_paiement', 'Rappel d’échéance de scolarité'), ('recu_paiement', 'Reçu de paiement sécurisé'), ('bulletin', 'Mise à disposition du bulletin'), ('general', 'Information générale')], max_length=30, verbose_name='Type d’événement')),
                ('canal', models.CharField(choices=[('sms', 'SMS Mobile'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=20, verbose_name='Canal')),
                ('destinataire', models.CharField(max_length=100, verbose_name='Destinataire (N° Tél. ou Email)')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente d’envoi'), ('envoye', 'Envoyé avec succès'), ('echec', 'Échec de transmission')], default='envoye', max_length=20, verbose_name='Statut')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Réf. Passerelle SMS/WhatsApp')),
                ('envoye_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date d’envoi')),
                ('declenche_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Déclenché par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_parents', to='dashboard.ecolesettings', verbose_name='École')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_parents', to='dashboard.etudiant', verbose_name='Élève concerné')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dashboard.tuteur', verbose_name='Tuteur destinataire')),
            ],
            options={
                'verbose_name': 'Notification Parent',
                'verbose_name_plural': 'Notifications Parents',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='LienTuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur_legal', 'Tuteur légal'), ('oncle', 'Oncle'), ('tante', 'Tante'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre responsable')], default='pere', max_length=30, verbose_name='Lien de parenté')),
                ('est_responsable_financier', models.BooleanField(default=True, verbose_name='Responsable financier (paiements)')),
                ('est_contact_urgence', models.BooleanField(default=True, verbose_name="Contact en cas d'absence ou urgence")),
                ('recoit_bulletin', models.BooleanField(default=True, verbose_name='Destinataire du bulletin')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_tuteurs', to='dashboard.etudiant')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_etudiants', to='dashboard.tuteur')),
            ],
            options={
                'verbose_name': 'Lien de parenté élève-tuteur',
                'verbose_name_plural': 'Liens de parenté élèves-tuteurs',
            },
        ),
        migrations.CreateModel(
            name='DecisionConseilClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Annuel', 'Bilan Annuel')], max_length=20, verbose_name='Période')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne obtenue')),
                ('rang', models.PositiveIntegerField(verbose_name='Rang dans la classe')),
                ('effectif', models.PositiveIntegerField(verbose_name='Effectif de la classe')),
                ('moyenne_classe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne de la classe')),
                ('moyenne_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Plus forte moyenne')),
                ('moyenne_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Plus faible moyenne')),
                ('mention', models.CharField(blank=True, choices=[('Tres Bien', 'Félicitations - Mention Très Bien (>=16)'), ('Bien', 'Félicitations - Mention Bien (>=14)'), ('Assez Bien', 'Compliments - Mention Assez Bien (>=12)'), ('Passable', 'Encouragements - Mention Passable (>=10)'), ('Tableau Honneur', 'Tableau d’Honneur'), ('Avertissement', 'Avertissement de travail (<10)'), ('Blame', 'Blâme de travail (<8)')], max_length=50, verbose_name='Mention')),
                ('decision_passage', models.CharField(blank=True, choices=[('admis', 'Admis(e) en classe supérieure'), ('redouble', 'Redouble la classe'), ('exclu', 'Exclu(e)'), ('admis_examen', 'Admis(e) à se présenter aux examens nationaux (DEF / BAC)'), ('en_attente', 'En attente de délibération')], max_length=30, null=True, verbose_name='Décision du conseil')),
                ('total_absences', models.PositiveIntegerField(default=0, verbose_name='Total absences')),
                ('total_retards', models.PositiveIntegerField(default=0, verbose_name='Total retards')),
                ('observations', models.TextField(blank=True, verbose_name='Observations du conseil')),
                ('date_validation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de délibération')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_conseil', to='dashboard.ecolesettings', verbose_name='École')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_conseil', to='dashboard.inscription', verbose_name='Inscription')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Président du conseil')),
            ],
            options={
                'verbose_name': 'Décision du Conseil de Classe',
                'verbose_name_plural': 'Décisions des Conseils de Classe',
                'ordering': ['-date_validation', 'rang'],
                'unique_together': {('inscription', 'periode')},
            },
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.UniqueConstraint(fields=('ecole', 'nom_salle'), name='uniq_salle_nom_par_ecole'),
        ),
        migrations.AddConstraint(
            model_name='lientuteur',
            constraint=models.UniqueConstraint(fields=('tuteur', 'etudiant'), name='uniq_lien_tuteur_etudiant'),
        ),
    ]
